{
    "name": "Aafaq Importer",
    "version": "1.0",
    "category": "Tools",
    "summary": "Import Customers from XLS/XLSX for the Aafaq only",
    "author": "Aafaq",
    "depends": ["base", "mail", "account", "sale", "contacts", "queue_job"],
    "data": [
        "security/ir.model.access.csv",
        "data/aafaq_import_sequence.xml",
        "data/aafaq_import_alias_data.xml",
        "data/aafaq_import_cron.xml",
        "views/aafaq_import_queue_views.xml",
        "views/aafaq_import_log_views.xml",
        "views/aafaq_import_held_mail_views.xml",
        "views/aafaq_import_alias_views.xml",
        "views/aafaq_map_attachment_views.xml",
        "views/account_mapping_views.xml",
        "views/product_mapping_views.xml",
        "views/res_partner_view.xml",
        "views/acount_move_view.xml",
        "wizard/aafaq_import_wizard_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
