{
    "name": "Purchase Request",
    "version": "1.4.1",
    "summary": "Employees can use this module to create request for items either Genaral  or IT category Items",
    "category": "Purchase Management",
    "depends": [
        "purchase_stock",
        "hr",
        "account_budget",
        "web_domain_field",
        "purchase_requisition",
    ],
    "data": [
        "security/purchase_request.xml",
        "security/ir.model.access.csv",
        "data/email_template.xml",
        "data/purchase_request_category_data.xml",
        "views/hr.xml",
        "wizard/purchase_request_create_rfq.xml",
        "views/purchase_order.xml",
        "views/product_category.xml",
        "views/stock_move_views.xml",
        # "reports/report_action.xml",
        # "reports/report_layout.xml",
        # "reports/report_view.xml",
        "views/budget.xml",
        "data/purchase_request_sequence.xml",
        "data/purchase_request_data.xml",
        "views/purchase_request_view.xml",
        "views/purchase_request_category_view.xml",
        "reports/expense_purchase_report_template.xml",
        "reports/office_supply_req_report_template.xml",
        "reports/canvas_sheet_report_template.xml",
        "reports/purchase_request_form_reports.xml",
    ],
    "license": "LGPL-3",
    "auto_install": False,
    "installable": True,
    "application": True,
}
